# Contrast Security Local Scan Engine - Azure DevOps Pipeline
# Main pipeline definition for scanning applications with Contrast Security Local Scan Engine

trigger:
  branches:
    include:
      - main
      - develop
      - feature/*
      - release/*

variables:
  - group: 'Contrast Security Credentials'
  - template: variables/contrast-variables.yml
  - name: buildConfiguration
    value: 'Release'

stages:
  # Build Stage
  - template: templates/build-template.yml
    parameters:
      buildConfiguration: $(buildConfiguration)

  # Security Scan Stage
  - template: templates/scan-template.yml
    parameters:
      dependsOn: Build
      artifactName: 'application-artifacts'

  # Deploy Stage (if security scan passes)
  - template: templates/deploy-template.yml
    parameters:
      dependsOn: SecurityScan
      condition: succeeded()
      artifactName: 'application-artifacts'
