# Build Stage Template for Contrast Security Integration
# This template defines the build stage for a typical Java application

parameters:
  - name: buildConfiguration
    type: string
    default: 'Release'
  - name: javaVersion
    type: string
    default: '11'

stages:
  - stage: Build
    displayName: 'Build Application'
    jobs:
      - job: BuildApplication
        displayName: 'Build Application'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          # Set up Java for the application build
          - task: JavaToolInstaller@0
            inputs:
              versionSpec: '${{ parameters.javaVersion }}'
              jdkArchitectureOption: 'x64'
              jdkSourceOption: 'PreInstalled'
            displayName: 'Set up Java ${{ parameters.javaVersion }}'
          
          # Build with Maven
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'package'
              options: '-DskipTests -Dbuild.configuration=${{ parameters.buildConfiguration }}'
              publishJUnitResults: false
              jdkVersionOption: '1.${{ parameters.javaVersion }}'
            displayName: 'Build with Maven'
          
          # Copy build artifacts to staging directory
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)/target'
              Contents: '*.jar'
              TargetFolder: '$(artifactPath)'
            displayName: 'Copy Build Artifacts'
          
          # Publish build artifacts
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(artifactPath)'
              ArtifactName: 'application-artifacts'
              publishLocation: 'Container'
            displayName: 'Publish Build Artifacts'
