# Deploy Stage Template for Contrast Security Integration
# This template defines the deployment stage that runs after security scanning passes

parameters:
  - name: dependsOn
    type: string
    default: 'SecurityScan'
  - name: condition
    type: string
    default: 'succeeded()'
  - name: artifactName
    type: string
    default: 'application-artifacts'
  - name: environment
    type: string
    default: 'Development'

stages:
  - stage: Deploy
    displayName: 'Deploy Application'
    dependsOn: ${{ parameters.dependsOn }}
    condition: ${{ parameters.condition }}
    jobs:
      - deployment: DeployApp
        displayName: 'Deploy Application'
        environment: ${{ parameters.environment }}
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          runOnce:
            deploy:
              steps:
                # Download build artifacts
                - task: DownloadBuildArtifacts@0
                  inputs:
                    buildType: 'current'
                    downloadType: 'single'
                    artifactName: '${{ parameters.artifactName }}'
                    downloadPath: '$(Build.ArtifactStagingDirectory)'
                  displayName: 'Download Build Artifacts'
                
                # Example deployment step (customize for your environment)
                - script: |
                    echo "Deploying application to ${{ parameters.environment }}..."
                    # Add actual deployment commands here
                    echo "Application deployed successfully!"
                  displayName: 'Deploy Application'
